### ISSUE TITLE
Disappears when ads play

### ISSUE THREAD

**Issue by ben-peng** [dvx/lofi#58]
Just found and really like the mini player. I'm on Windows 10 and whenever an ad plays, the mini player disappears, only returning if I close and re-open.

**Comment by burritosoftware** [comment]
I have this too.

**Comment by burritosoftware** [comment]
@dvx

**Comment by dvx** [comment]
Yeah this is a known issue, I need to push a fix. I pay for Spotify, so not an issue for me, but on it!

**Comment by dvx** [comment]
Fixed this and will be available in the next release (1.5, hopefully by end of week).

**Comment by RevengeSeeker** [comment]
> Fixed this and will be available in the next release (1.5, hopefully by end of week).
I'm sorry but this is not fixed indeed, it's still happening.

**Comment by RevengeSeeker** [comment]
I'm sorry but this is not fixed, it's still happening. Any preview on when it will be fixed?

**Comment by dvx** [comment]
Should be fixed in the newest release! Please re-download and install Lofi 1.5.0!
